codebreakdown/togls

.travis.yml
README.md
Rakefile

Enabled Travis-CI builds so that we could make sure that the test suite stays as awesome as it is right now.

Enable travis ci builds

---

ChangeLog.md
README.md
lib/tasks/togls.rake
lib/togls.rb
lib/togls/errors.rb
lib/togls/feature.rb
lib/togls/feature_registry.rb
lib/togls/rules.rb
lib/togls/rules/boolean.rb
spec/features/togls_spec.rb
spec/lib/togls/feature_registry_spec.rb
spec/lib/togls/feature_spec.rb
spec/lib/togls/rules/boolean_spec.rb
spec/lib/togls_spec.rb

This pull request includes the following significant changes.
- It changes the define feature toggle api to **require** a human readable description. I did this as an opinionated attempt at getting people to actually describe what their feature toggles are for so that after they have been around for a bit people can still understand them.
- Added a rake task to output all the features toggles in the system **state** (`on`, `off`, `?` - unknown due to *Complex Rule*), **key**, and **human readable description**. I saw this being useful for reviewing a systems feature toggles from time to time.
- Revamp of the `README.md` to include new description based features, but also to better explain the concept of Rules and their requirements.
This should resolve issue #5.

Require human readable description

---

lib/togls/feature_registry.rb

I eliminated the `tap()` call in this because the `Feature#on` method
returns `self`, which is the instance of the `Feature` itself.
Therefore, it would be the same as what the `tap()` call is doing. I
suspect this was done maybe before the `on()` method returned `self`.
Either way, now it seems useless to use a `tap()` call there.
You can see the `on()` definition return `self` at the following.
https://github.com/codebreakdown/togls/blob/master/lib/togls/feature.rb#L16

Eliminate a useless `tap()` call

---

ChangeLog.md
README.md
lib/togls.rb
lib/togls/feature.rb
lib/togls/feature_registry.rb
lib/togls/rule.rb
lib/togls/rules.rb
lib/togls/rules/boolean.rb
lib/togls/rules/boolean_env_override.rb
lib/togls/rules/group.rb
spec/features/togls_spec.rb
spec/lib/togls/feature_registry_spec.rb
spec/lib/togls/feature_spec.rb
spec/lib/togls/rule_spec.rb
spec/lib/togls/rules/boolean_env_override_spec.rb
spec/lib/togls/rules/boolean_spec.rb
spec/lib/togls/rules/group_spec.rb
spec/lib/togls_spec.rb

I did this so that users could override their feature toggles at runtime based
on the environment the application is running in. I also added a Provided
Rules Reference to the README.md to aid people in understand what rules exist
and how they can use them.
*Note:* This includes the changes from pull request https://github.com/codebreakdown/togls/pull/9  as it is a dependency of this pull request.

Add boolean env override rule

---

ChangeLog.md
lib/togls/toggle.rb
spec/features/togls_spec.rb
spec/lib/togls/toggle_spec.rb

I did this because I want a way to ask if a feature is `off?` not just `on?`.
This is a little sugar but it will be helpful in some situations. I see this
as helpful when you are changing behavior.
Some examples would be:
```ruby
do_some_stuff if Togls.feature(:new_feature).off? && some_other_conditional
#or
if Togls.feature(:new_feature).off?
do_old_stuff
end
```

Add an `off?` conditional method for features

---

ChangeLog.md
lib/togls.rb
spec/lib/togls_spec.rb

I did so that there wouldn't be a way from the external API screw
yourself by having a nil feature toggle registry. More specifically,
prior to this if you were to set `Togls.features = nil` and then try and
evaluate a feature toggle it would throw an exception, :-). This
resolves issue #19.

Make Togls.feature create empty toggle registry

---

ChangeLog.md
lib/togls/toggle_repository_drivers/env_override_driver.rb
spec/features/togls_spec.rb
spec/lib/togls/toggle_repository_drivers/env_override_driver_spec.rb

I did this so that the only valid values for an environment variable
override are true/false. This means that any other value than true or
false will now result in the feature toggle falling back to the in
memory value for that feature toggle. Issue #21.
@RyanHedges @BRIMIL01 I could use a peer review on this, :-)

Make env override use true/false

---

DEVELOPMENT.md

I did this so that people that wanted to contribute to this project
would have somewhere to go to find information to aid them in
understanding and contributing to the code.
How the change addresses the need:
This provides them details on where they should start and what they
should focus on initially (being end user experience and docs), as well
as where they should focus secondarily (understanding the architecture
within the context of the end user experience).

Add starter DEVELOPMENT.md

---

LICENSE.txt

I did this so that it was clear that the copyright spans from 2015 through 2016.

Bump copyright to include 2016

---

lib/togls/feature_toggle_registry.rb
lib/togls/test_toggle_registry.rb
spec/lib/togls/feature_toggle_registry_spec.rb
spec/lib/togls/test_toggle_registry_spec.rb

I made this change to cleanup the code so there is less noise.
How the change addresses the need:
This helps accomplished this goal because it removes instance variables that
were accidentally left in the code base that are not actually used.

Remove useless instance variables

---

CHANGELOG.md
lib/togls/feature_repository_drivers/in_memory_driver.rb
lib/togls/rule_repository_drivers/in_memory_driver.rb
lib/togls/toggle_repository_drivers/in_memory_driver.rb

I did this so that Togls could be safely used in a threaded environment. I prime
example of this would be a web application run via puma.
How the change addresses the need:
The only real modifiable state is stored within the drivers so we didn't need
to add any synchronization above the repository driver layers.

Make Togls drivers thread-safe

---

CHANGELOG.md
lib/togls/feature_repository_drivers/in_memory_driver.rb
lib/togls/rule_repository_drivers/in_memory_driver.rb
lib/togls/toggle_repository_drivers/in_memory_driver.rb
spec/togls/feature_repository_drivers/in_memory_driver_spec.rb
spec/togls/rule_repository_drivers/in_memory_driver_spec.rb
spec/togls/toggle_repository_drivers/in_memory_driver_spec.rb

I did this because there was a rare timing issue with multi-threading where
references to sub-hashes and sub-values of a hash that were of certain types
where being incorrectly shared.
How the change addresses the need:
Adding the Marshaling in the set, get, and all methods of the drivers resolves
this issue because it basically causes a deep copy of the objects. It also has
the added benefit of matching the behavior of say the Redis driver and most
others that would also require marshaling.

Add Marshal to in-memory driver set, get, all

---

CHANGELOG.md
lib/togls.rb
lib/togls/feature_toggle_registry.rb
lib/togls/feature_toggle_registry_manager.rb
lib/togls/test_toggle_registry.rb
spec/spec_helper.rb
spec/togls/feature_toggle_registry_manager_spec.rb
spec/togls/feature_toggle_registry_spec.rb
spec/togls/test_toggle_registry_spec.rb
spec/togls_spec.rb

I did this so that a single feature repository would be able to be
shared across multiple repositories potentially.
I did this because it was duplicative of the responsibility of building
a registry. I modified the initialize method of both the
FeatureToggleRegistry class and the TestToggleRegistry class to accept
on optional block so that they can be used in a similar fashion to how
create was previously used. This also will allow a registry to have
arguments during construction in addition to the block that created
didn't really allow for.
I did this so that the memoization and lazy creation of the
FeatureToggleRegistry that was previously duplicated in two places could
be streamlined into one private method …

Move feature repository out

---

CHANGELOG.md
lib/tasks/togls.rake
lib/togls/feature_toggle_registry_manager.rb
spec/togls/feature_toggle_registry_manager_spec.rb
spec/togls_spec.rb

I did this to better communicate the intent and associated registry that
is used by that DSL interface. It also opens us up to theoretically
adding support for other classifications of toggles in the future.
This relates to issue #38 .

Change Togls.features to Togls.release

---

CHANGELOG.md
lib/togls/feature_toggle_registry_manager.rb
spec/togls/feature_toggle_registry_manager_spec.rb
spec/togls_spec.rb

I did this so that there would be a convenient way to manage enabling
and disabling test mode for you when you can use a block.
Relates to issue #44 .

Add `test_mode` method

---

CHANGELOG.md
lib/tasks/togls.rake
spec/togls_spec.rb

I did this because this feature turned out to not be that valuable and
we don't want to have to pay the maintenance cost of keeping it around.

Remove togls:features rake task

---

CHANGELOG.md
lib/togls/errors.rb
lib/togls/feature_repository.rb
lib/togls/release_toggle_registry.rb
spec/spec_helper.rb
spec/togls/feature_repository_spec.rb
spec/togls/release_toggle_registry_spec.rb
spec/togls_spec.rb

I did this because we don't want the state of release feature toggles to be
defined multiple times. This could cause developers to create toggles that they
think to be unique to their needs but in actuality could be turning a previously
defined feature on or off erroneously.

Add an exception for when a feature has already been defined

---

CHANGELOG.md
lib/togls/rule.rb
lib/togls/rule_type_repository.rb
lib/togls/rule_type_repository_drivers/in_memory_driver.rb
lib/togls/rules/boolean.rb
lib/togls/rules/group.rb
spec/togls/rule_spec.rb
spec/togls/rule_type_repository_drivers/in_memory_driver_spec.rb
spec/togls/rule_type_repository_spec.rb
spec/togls/rules/boolean_spec.rb
spec/togls/rules/group_spec.rb
spec/togls_spec.rb

I did this so that the rule type meta data (title, description) would
now be stored via the rule type repository.
This relates to issue #62

Add meta data storage to rule type repository

---

CHANGELOG.md
lib/togls.rb
lib/togls/errors.rb
lib/togls/feature.rb
lib/togls/feature_repository.rb
lib/togls/null_toggle.rb
lib/togls/rule.rb
lib/togls/target_types.rb
lib/togls/toggle.rb
lib/togls/toggle_registry.rb
lib/togls/toggle_repository.rb
spec/togls/feature_repository_spec.rb
spec/togls/feature_spec.rb
spec/togls/rule_spec.rb
spec/togls/rules/boolean_spec.rb
spec/togls/rules/group_spec.rb
spec/togls/toggle_registry_spec.rb
spec/togls/toggle_repository_spec.rb
spec/togls/toggle_spec.rb
spec/togls_spec.rb

Issue #65 
The goal of this was to add support for defining abstract formalized target types in the DSL as well as implement basic target type checking and handle miss-match scenarios appropriately.

Add target type to feature definition

---

CHANGELOG.md
lib/togls/rule.rb
lib/togls/rule_repository.rb
lib/togls/toggle.rb
lib/togls/toggle_repository.rb
spec/togls/rule_repository_spec.rb
spec/togls/rule_spec.rb
spec/togls/toggle_repository_spec.rb
spec/togls/toggle_spec.rb

This PR intends to add rule instance target_types so that instances of rules can have a specified target_type. This PR relates to issue #67.
I did this so that when the RuleRepository attempts to store a rule it now
stores the target_type associated with that rule along with the data and type
information it was previously storing.
I did this because I want to add support for in code and externally defined
rules to be able to specify a given target_type. That way for example if you
were defining a rule instance called alpha_testers from the Group rule you would
be able to type match appropriately. For example:
alpha_testers = Togls::Rules::Group.new([323, 11, 34, 123], target_type: :user_id)
This would allow us to do checking based on the …

Add rule target type

---

lib/togls/feature.rb
lib/togls/rule.rb
lib/togls/target_types.rb
lib/togls/toggle.rb
lib/togls/toggle_registry.rb
spec/togls/feature_spec.rb
spec/togls/rule_spec.rb
spec/togls/rules/boolean_spec.rb
spec/togls/rules/group_spec.rb
spec/togls/toggle_spec.rb

I did this so we can start using these types for type checking. This does not
address all the concerns we have around NOT_SET type checking vs NONE. This
only transitions us out of using ANY for NOT_SET.

Remove ANY and add NOT_SET and NONE

---

lib/togls/feature.rb
lib/togls/rule.rb
lib/togls/rules/boolean.rb
lib/togls/toggle.rb
spec/togls/feature_spec.rb
spec/togls/rule_spec.rb
spec/togls/rules/boolean_spec.rb
spec/togls/toggle_spec.rb
spec/togls_spec.rb

relates to https://github.com/codebreakdown/togls/issues/73
I did this so that we can verify that the rule and feature can be evaluated
properly. If there is a mismatch it will return false and later return a type
of null toggle. This requires us to change the boolean rule to have the
correct default target type of NONE instead of being NOT_SET.

Correct target type checking logic

---

lib/togls/errors.rb
lib/togls/rule.rb
spec/togls/rule_repository_spec.rb
spec/togls/rule_spec.rb
spec/togls/rules/group_spec.rb
spec/togls/toggle_spec.rb
spec/togls/toggler_spec.rb

I did this so that it will raise an exception when constructing a rule that
doesn't have a target type set.

Make rule require target type to construct

---

lib/togls/toggle.rb
spec/togls/toggle_spec.rb

I did this because there are some target type states in rules and features
that should never ever happen. If they happen we want to log it so that you
can find and correct the problem.
Relates to [this issue](https://github.com/codebreakdown/togls/issues/69)

Add logging for when rules and features are in erroneous state

---

CHANGELOG.md
lib/togls.rb
lib/togls/default_feature_target_type_manager.rb
lib/togls/errors.rb
lib/togls/feature.rb
lib/togls/null_toggle.rb
lib/togls/toggle_registry.rb
spec/spec_helper.rb
spec/togls/default_feature_target_type_manager_spec.rb
spec/togls/feature_repository_drivers/in_memory_driver_spec.rb
spec/togls/feature_repository_spec.rb
spec/togls/feature_spec.rb
spec/togls/null_toggle_spec.rb
spec/togls/toggle_registry_spec.rb
spec/togls/toggle_repository_drivers/in_memory_driver_spec.rb
spec/togls/toggle_repository_spec.rb
spec/togls/toggle_spec.rb
spec/togls_spec.rb

I did this so that the DSL could still be the clean simple dsl we like in the
majority of cases. I also made feature require target_type as an argument to
construction similar to how we did with rule previously.

Add default feature target type

---

CHANGELOG.md
lib/togls/errors.rb
lib/togls/toggle.rb
spec/togls/toggle_spec.rb
spec/togls_spec.rb

I did this so that when a feature is evaluated in code developers can be
informed before deployment when there is a feature target type contract
breach.
This compares the evaluation target against the expectations of the features
target type contract and raises appropriate exceptions in the contract breach
scenarios.
Relates to #78

Feature validates argument during evaluation

---

lib/togls/null_toggle.rb
lib/togls/target_types.rb
lib/togls/toggle.rb
spec/togls/null_toggle_spec.rb
spec/togls/toggle_spec.rb
spec/togls_spec.rb

The goal of this was to fix the NullToggle behavior with the new type checking we have added so that it behaves as it did before. Which is to evaluate to false when dealing with a null toggle.

Fix null toggle null feature target type

---

CHANGELOG.md
lib/togls/errors.rb
lib/togls/feature_repository.rb
lib/togls/rule_repository.rb
lib/togls/rule_repository_drivers/env_override_driver.rb
lib/togls/toggle_repository.rb
spec/togls/feature_repository_spec.rb
spec/togls/rule_repository_drivers/env_override_driver_spec.rb
spec/togls/rule_repository_spec.rb
spec/togls/toggle_repository_spec.rb

This adds the necessary handling of exceptions to the toggle reconstitution process.
It accomplishes this by first adding payload validation checking to both the rule and feature repositories so that they can identify and report invalid payloads via exception up to the toggle reconstitution process in the toggle repository.
This also includes fixes to add the `target_type` to the rule environment override driver which we missed and the validation checker aided in identifying.
This is my solution for #80

Handle exceptions during reconstitution

---

lib/togls/rule_repository_drivers/env_override_driver.rb
lib/togls/toggle_repository_drivers/env_override_driver.rb
spec/togls/rule_repository_drivers/env_override_driver_spec.rb
spec/togls/toggle_repository_drivers/env_override_driver_spec.rb

I did this because it was broken without this change since rules now require the
type_id, etc.

Fix env override drivers to use new rule

---

lib/togls/rule_manager.rb

I did this so that the code would be cleaned up a bit and so that it would make
it easier to integrate additional drivers.

Extract rule repository drivers into a method

---

lib/togls/null_toggle.rb
lib/togls/toggle_registry.rb
lib/togls/toggle_repository.rb
lib/togls/toggle_repository_drivers/env_override_driver.rb
lib/togls/toggle_repository_drivers/in_memory_driver.rb
spec/togls/toggle_registry_spec.rb
spec/togls/toggle_repository_drivers/env_override_driver_spec.rb
spec/togls/toggle_repository_drivers/in_memory_driver_spec.rb
spec/togls/toggle_repository_spec.rb
spec/togls_spec.rb

I did this because previously when toggle reconstitution would fail due to a
miss-match, or a missing value, etc. It would simply return a NullToggle. This
short-circuited the process and resulted in the toggle evaluating to false. The
problem was that it was not falling back to the other toggle drivers and
eventually falling back to the defaults held by the in-memory drivers.
I resolved this by modifying the toggle repository `get` method to check the
success/failure of toggle reconstitution and fall back to the previous toggle
drivers if reconstitution failed. This will make it so that if for any of the
above possible reasons for failure, it will follow the natural driver fallback
path rather than short-circuiting with a NullToggle.

Make fallback resort to next toggle driver

---

CHANGELOG.md
lib/togls/rule.rb
lib/togls/rule_manager.rb
lib/togls/rule_repository.rb
lib/togls/rule_repository_drivers/env_override_driver.rb
lib/togls/rules/boolean.rb
lib/togls/toggle.rb
lib/togls/toggle_repository.rb
lib/togls/toggle_repository_drivers/env_override_driver.rb
lib/togls/toggler.rb
spec/togls/rule_repository_drivers/env_override_driver_spec.rb
spec/togls/rule_repository_spec.rb
spec/togls/rule_spec.rb
spec/togls/rules/boolean_spec.rb
spec/togls/rules/group_spec.rb
spec/togls/toggle_repository_drivers/env_override_driver_spec.rb
spec/togls/toggle_repository_spec.rb
spec/togls/toggle_spec.rb
spec/togls/toggler_spec.rb
spec/togls_spec.rb

I did this so that rules would exist and be identified by an abstract identifier
while still being modified.

Make rules identified by abstract string rule id

---

CHANGELOG.md
lib/togls.rb
lib/togls/feature_toggle_registry_manager.rb
spec/togls/feature_toggle_registry_manager_spec.rb
spec/togls_spec.rb
togls.gemspec

I did this so that we could log safely using an application controlled logger vs the hard coded STDOUT logger we had before with the default log level.

Replace logger with optional logger

---

CHANGELOG.md
lib/togls.rb
togls.gemspec

I did this so that we are using the latest stable release of
optional_logger. Even though this was a major bump for optional_logger
it doesn't change the interface that we expose at all. Therefore, it is
just a minor version bump.

Upgrade optional_logger to v2.0.0
